version: '3.9'
services:
  mysql:
    container_name: ivs_mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ivs
    networks:
      - nodejs
  api:
    container_name: ivs_app
    restart: on-failure
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    volumes:
      - .:/var/app
    networks:
      - nodejs
  nginx:
      image: nginx:alpine
      restart: always
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      links:
        - api:api
      networks:
        - nodejs
networks:
  nodejs: